CREATE TABLE transactions (
    CATEGORY TEXT,
    AMOUNT INTEGER,
    RECIPIENT TEXT,
    TRANSACTION_TYPE TEXT,
    date TIMESTAMP,
    MESSAGE_BODY TEXT
);

CREATE TABLE logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message TEXT,
    error_reason TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
